### ISSUE TITLE
s.toFixed is not a function in the widget CDN plugin

### ISSUE THREAD

**Issue by JTorresConsulta** [DePayFi/widgets#130]
I am reporting it :) 

VM601:26 WebSocket connection to 'wss://walletconnect.depay.com/?env=browser&host=xxxxx.top&protocol=wc&version=1' failed: 

![Image](https://github.com/user-attachments/assets/eecc4a2b-2c78-44cf-8231-06f7c2d63296)

**Comment by 0xNe0x1** [comment]
Please upgrade. Error should be fixed.

**Comment by JTorresConsulta** [comment]
I am loading this CDN version, but the issue still happend when I open Metamask:

https://sdk.depay.com/widgets/v12.18.5.js

**Comment by JTorresConsulta** [comment]
Navigator errors:


Refused to frame 'https://verify.walletconnect.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://*.depay.com https://depay.com https://localhost:* http://localhost:* https://*.localhost:* http://*.localhost:* https://127.0.0.1:* http://127.0.0.1:*".
Entender este error

Refused to frame 'https://verify.walletconnect.org/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://*.depay.com https://depay.com https://localhost:* http://localhost:* https://*.localhost:* http://*.localhost:* https://127.0.0.1:* http://127.0.0.1:*".

VM4904:129 TypeError: s.toFixed is not a function
    at <anonymous>:190:205587
    at XV (<anonymous>:129:93118)
    at vG (<anonymous>:129:113574)
    at iG (<anonymous>:129:105921)
    at UW (<anonymous>:129:46834)
    at <anonymous>:129:112375
    at gG (<anonymous>:129:112380)
    at eG (<anonymous>:129:105440)
    at A (<anonymous>:110:2143)
    at MessagePort.S (<anonymous>:110:2675)

**Comment by JTorresConsulta** [comment]
of course, it is the base:


`
        var currency_amount = 50;

          DePayWidgets.Payment({
            currency: 'USD',
            style: {
              colors: {
                primary: '#00aa00',
                text: '#111111',
                buttonText: '#ffffff',
                icons: '#333333'
              }
            }, 
            closed: ()=> {   },
            error: (error)=> {   },
            critical: (error)=> {   },
            failed: (transaction)=> {   },
            sent: (tx)=> {
              var res = JSON.parse(JSON.stringify(tx))
              console.log("_succeeded: " + res._succeeded )
            },
            succeeded: (tx, info)=> {
  
              var info = JSON.parse(JSON.stringify(info))
              console.log("**PAYMENT INFO**: " + JSON.stringify(info))

              var tx = JSON.parse(JSON.stringify(tx))
              
              if(tx._succeeded){
                  //...
              }
            },
            amount: {
              fix: currency_amount,
              currency: 'USD'
            },
            accept: [
              {
                blockchain: 'polygon',
                token: '0x27xxxxxxxxxxxxxxxxxxx', //USDC
                receiver: '0xfxxxxxxxxxxxxxxxxx'
              },
              ...
            ] 
      
          });
      
`

**Comment by 0xNe0x1** [comment]
could you please perform a console.log(currency_amount) before you pass the configuration and let me know what the output is?

**Comment by 0xNe0x1** [comment]
just to make 100% sure it reflects what you provided with:

```
var currency_amount = 50;
```

**Comment by 0xNe0x1** [comment]
also, if you already have it configured to receive USDC, you should move the amount configuration to accept and drop the top level amount configuration entirely:

```
amount: null,
accept: [
  {
    blockchain: 'polygon',
    amount: 50,
    token: '0x27xxxxxxxxxxxxxxxxxxx', //USDC
    receiver: '0xfxxxxxxxxxxxxxxxxx'
  }
]
```

that likely gets you passed the error.

**Comment by 0xNe0x1** [comment]
additionally, can you try to upgrade to widget version 13 and see if you have the same problem in the new version?

**Comment by 0xNe0x1** [comment]
there is a working currency variant on the demo page: https://depayfi.github.io/widgets/demo.bundle.html
Search for "Payment: with fixed currency amount"

See code: https://github.com/DePayFi/widgets/blob/main/demo.bundle.html#L927-L956

There is also an automated test here: https://github.com/DePayFi/widgets/blob/main/cypress/e2e/Payment/fix-currency-amounts.js#L25-L35

**Comment by JTorresConsulta** [comment]
My real code structure:

I accept a lot of chains to receive USDC. 
My wish is that the payer sends any crypto currency but I always receive stable coins (USDC)
In the past works.


`var currency_amount = 50
          
          DePayWidgets.Payment({
            currency: 'USD',
            closed: ()=> {   },
            error: (error)=> {   },
            critical: (error)=> {   },
            failed: (transaction)=> {   },
            sent: (tx)=> {
              console.log("Crypto Payment sent:")
              //console.log("sent transaction: " + JSON.stringify(tx) )
              var res = JSON.parse(JSON.stringify(tx))
              console.log("_succeeded: " + res._succeeded )
            },
            succeeded: (tx, info)=> {
              //console.log("succeeded transaction: " + JSON.stringify(tx) )
              var info = JSON.parse(JSON.stringify(info))
              console.log("**PAYMENT INFO**: " + JSON.stringify(info))

              var tx = JSON.parse(JSON.stringify(tx))
              console.log("_succeeded: " + tx._succeeded )
              console.log("url: " + tx.url )
              
              if(tx._succeeded){
                //My code
              }
            },
            amount: {
              fix: currency_amount,
              currency: 'USD'
            },
            accept: [
              {
                blockchain: 'polygon',
                token: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', //USDC
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'polygon',
                token: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F', //USDT
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'bsc',
                token: '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56',
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'ethereum',
                token: '0x6B175474E89094C44Da98b954EedeAC495271d0F',//DAI
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'ethereum',
                token: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', //USDC
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'ethereum',
                token: '0xdAC17F958D2ee523a2206206994597C13D831ec7', //USDT
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'gnosis',
                token: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', //xDAI
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'gnosis',
                token: '0x4ECaBa5870353805a9F068101A40E0f32ed605C6',//USDT
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'gnosis',
                token: '0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83', //USDC
                receiver: '0x00000000000000'
              }, 
              {
                blockchain: 'optimism',
                token: '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85', //USDC
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'optimism',
                token: '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58', //USDT
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'arbitrum',
                token: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831', //USDC
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'arbitrum',
                token: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9', //USDT
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'fantom',
                token: '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75',//USDC
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'fantom',
                token: '0x1B27A9dE6a775F98aaA5B90B62a4e2A0B84DbDd9',//USDT
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'avalanche',
                token: '0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e', //USDC
                receiver: '0x00000000000000'
              },
              {
                blockchain: 'avalanche',
                token: '0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7', //USDT
                receiver: '0x00000000000000'
              },
            ] 
      
          });`



---

Testing with V13

: /

No widget appeared, and the console says: "Critical error: You need to set a supported blockchain!"

Okay, I'm going to recreate the entire script based on your examples and I'll let you know

**Comment by 0xNe0x1** [comment]
also, the callbacks you are using, are no longer supported in v13, see release notes:
https://github.com/DePayFi/widgets/releases/tag/v13.0.0
`before, sent, succeeded, failed and validated callbacks are no longer supported`

**Comment by JTorresConsulta** [comment]
Ok, working.

I write "amount" in each accepted address and works again
